### ISSUE TITLE
Support a simpler script file API for non-experienced Groovy/Java programmers

### ISSUE THREAD

**Issue by peasoupio** [peasoupio/inv#104]
**Is your feature request related to a problem? Please describe.**
Some may find it simpler and more "conventional" to use INV without a "no-boundaries" Groovy script file.
It would allow less experienced programmers to get a grasp at INV without the Java/Groovy learning curve.

**Describe the solution you'd like**
Something like Jenkins Script vs Jenkins Declarative Pipeline, 

**Describe alternatives you've considered**
Maybe a YAML model?

**Additional context**
n/a

**Comment by peasoupio** [comment]
Jenkins Declarative Pipeline uses its own "Groovy" parser which does not allow arbitrary code definition.  
Per example, you can't simply define a variable using "def", without being outside of a "script" code block
```groovy
step {
   def notOk = true

   script {
       def isOk = true
   }
}
```

For a quicker solution, YAML seems to be a better candidate.

**Comment by peasoupio** [comment]
Here's what a YAML INV file would look like:
```yaml
name: my-inv

# Handle tags + String interpolation
tags:
  my: ${name}

workflow:
  # Casual "broadcast"
  - broadcast:
      name: Server

      # Returns a "string-interpolated" Map object.
      ready: |
        return [
          my: "${name}"
        ]

  # Casual require
  - require:
      name: Server

      # Validate response content
      resolved: |
        assert response.my == name
```
