### ISSUE TITLE
Allow nginx-ingress redirect/rewrite to work with the API

### ISSUE THREAD

**Issue by peasoupio** [peasoupio/inv#99]
**Is your feature request related to a problem? Please describe.**
When using nginx-ingress (with Kubernetes), static files are rewritten, but API calls use the "default" ("/") path instead of the new one.
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: composer
spec:
  rules:
    - host: localhost
      http:
        paths:
        - backend:
            serviceName: composer
            servicePort: 5050
          path: /composer(/|$)(.*)
```

**Describe the solution you'd like**
In the previous examples, API (xhr calls) should use the "/composer" path instead of "/".

**Describe alternatives you've considered**
Axios has a baseURL configuration and since Composer is a SPA, something like this should work:
```
// Allow nginx redirection
window.axios.defaults.baseURL = window.location.href.substr(0, window.location.href.lastIndexOf("/")) + "/"
```
